name: Run Daily Weather Fetch

on:
  schedule:
    # Run at 10:00 AM UTC 
    - cron: '0 10 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
    contents: write # Grand write permissions to push changes

jobs:
  run-weather:
    runs-on: ubuntu-latest  # Use Ubuntu VM

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Set up  bash and wget
    - name: Set up bash and wget
      run: sudo apt-get update && sudo apt-get install -y wget

    # Run the weather script
    - name: Run weather script
      run: bash weather.sh  
    
    # Commit and push the new weather data
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      run: |
        git config --global user.name "github-actions[bot]"
        
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        git add data/weather/*.json
        
        git commit -m "Update weather data for $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

        git push origin main


